name: Test/Build

concurrency:
  group: testbuild-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  merge_group: {}

jobs:
  test_build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v5
        with:
          submodules: 'true'
      - name: Set up NodeJS
        uses: actions/setup-node@v6
        with:
          node-version: lts/*
          check-latest: true
          cache: npm
          cache-dependency-path: package-lock.json
      - name: Set up Emscripten
        uses: mymindstorm/setup-emsdk@v14 
      - run: npm ci
      - run: npm run lint
      - run: npm run build
      - run: npm run testOnly
      - run: cp LICENSE dist/
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/
